### ISSUE TITLE
NameError: name 'wall_tile' is not defined

### ISSUE THREAD

**Issue by BrunoRochaDev** [dgomes/ia-rush#1]
The 'common.py' script throws an error at line 74 as it tries to access the class variable 'wall_tile' without using 'self'.

**Comment by dgomes** [comment]
fixed by [8ca7e3e](https://github.com/dgomes/ia-rush/commit/8ca7e3e93755e7efeab17d1a06f1514d7e6824f7)

**Comment by BrunoRochaDev** [comment]
Fixed!
