### ISSUE TITLE
Selected car makes a crazy movement

### ISSUE THREAD

**Issue by dgomes** [dgomes/ia-rush#4]
Currently there are two open PR's for the same issue:
- Selected car makes a crazy movement leading to a out of sync situation between car and cursor

PR #2 skips the selected car
PR #3 adjusts the the cursor

**Comment by dgomes** [comment]
IMHO #3 is a better approacher, but please discuss :)

**Comment by jteles277** [comment]
In my opinion, even though the PR #3 is a more complex solution, from a game design point of view the PR #2 is a better approach

**Comment by dgomes** [comment]
31534eb6cb79330b5ecb3086c93975aebb5108b5 fixes the issue
